spring:
  profiles:
    active: export
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n/message